version: '3.1'
services:
  db:
    image: mysql
    container_name: slbfe_container
    environment:
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - slfbe_data:/var/lib/mysql

volumes:
  slfbe_data: