server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost/slbfe?useSSL=false
    username: root
    password: 168@Montez
  jpa:
    hibernate:
      ddl-auto: update
